### POST request login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": "user2",
  "password": "user2"
}
> {% client.global.set("auth_token", response.body.token); %}

### GET request listar
GET http://localhost:3000/api/users
Authorization: Bearer {{auth_token}}


### POST request adicionar
POST http://localhost:3000/api/users
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "user2",
  "password": "user2"
}

### GET findBy
GET http://localhost:3000/api/users/2
Authorization: Bearer {{auth_token}}

### UPDATE
PUT http://localhost:3000/api/users/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "user2",
  "password": "user2"
}

### PATCH
PATCH http://localhost:3000/api/users/2
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "user2",
  "status": "inactive"
}

### GET findBy task
GET http://localhost:3000/api/tasks
Authorization: Bearer {{auth_token}}

### POST task
POST http://localhost:3000/api/tasks
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "task22"
}

### GET findBy task
GET http://localhost:3000/api/tasks/8
Authorization: Bearer {{auth_token}}

### UPDATE task
PUT http://localhost:3000/api/tasks/8
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "task22 modificada",
  "user_id": 3,
  "done": true
}

### PATCH task
PATCH http://localhost:3000/api/tasks/8
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "done": false
}

### DELETE task
DELETE http://localhost:3000/api/tasks/1
Authorization: Bearer {{auth_token}}

### GET findBy task and user
GET http://localhost:3000/api/tasks/3/user
Authorization: Bearer {{auth_token}}
